import turtle
def jump():
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def A():
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def B():
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def C():
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def D():
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def E():
    turtle.fd(5)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def F():
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def G():
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def H():
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def I():
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def J():
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def K():
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def L():
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def M():
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def N():
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def O():
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def P():
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def Q():
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def R():
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def S():
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def T():
    turtle.fd(20)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def U():
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def V():
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def W():
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def X():
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def Y():
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

def Z():
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(20)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(10)
    turtle.pd()
    turtle.fd(5)
    turtle.pu()
    turtle.fd(30)
    turtle.pd()

while True:
    a=input("Enter a sentence: ")
    turtle.reset()
    turtle.pu()
    turtle.backward(200)
    turtle.pd()
    turtle.width(5)
    turtle.pu()
    turtle.backward(100)
    turtle.pd()
    for i in a:
        i=i.upper()
        if i=="A":
            A()
        elif i=="B":
            B()
        elif i=="C":
            C()
        elif i=="D":
            D()
        elif i=="E":
            E()
        elif i=="F":
            F()
        elif i=="G":
            G()
        elif i=="H":
            H()
        elif i=="I":
            I()
        elif i=="J":
            J()
        elif i=="K":
            K()
        elif i=="L":
            L()
        elif i=="M":
            M()
        elif i=="N":
            N()
        elif i=="O":
            O()
        elif i=="P":
            P()
        elif i=="Q":
            Q()
        elif i=="R":
            R()
        elif i=="S":
            S()
        elif i=="T":
            T()
        elif i=="U":
            U()
        elif i=="V":
            V()
        elif i=="W":
            W()
        elif i=="X":
            X()
        elif i=="Y":
            Y()
        elif i=="Z":
            Z()
        elif i==" ":
            turtle.fd(30)
        else:
            print('error')
